spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl


logging.level:
  org.hibernate.SQL: debug