spring:
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true

    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 12

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  profiles:
    active: local

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**


logging.level:
  org.hibernate.SQL: debug

logging:
  level:
    org.springframework.security: TRACE


