spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

  profiles:
    active: local

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**


logging.level:
  org.hibernate.SQL: debug